### ISSUE TITLE
Jenkins 2 compatibility

### ISSUE THREAD

**Issue by gbraad** [rdo-infra/weirdo#10]
Currently testing Jenkins 2.0, as noticed that the requirements for jenkins/README.rst are not correct. Executing Python scripts seems to be a plugin that is not mentioned in the install.

**Comment by gbraad** [comment]
https://review.gerrithub.io/270638

**Comment by gbraad** [comment]
Also, on 2.0 the configuration of Python has moved location to: http://[url]/configureTools/ or "Global Tool Configuration". This is a change that might be needed when upgrading to the latest version when GA.

**Comment by dmsimard** [comment]
I added a comment in the review, this doesn't seem to be required for us right now.
I've asked around and it doesn't look like we'll be upgrading to Jenkins 2 in the short term but it's good to keep track of that. Let's keep the issue opened and I edited the title.

**Comment by dmsimard** [comment]
FYI shiningpanda is no longer used. Pure shell and tox now.

**Comment by gbraad** [comment]
Noticed this... you refactored it ;-)

**Comment by dmsimard** [comment]
Yeah, sorry -- I'll update the docs ASAP.
