### ISSUE TITLE
Support rpm-based releases (i.e, rdo-release.rpm)

### ISSUE THREAD

**Issue by dmsimard** [rdo-infra/weirdo#4]
Right now WeIRDO is wired to use delorean repositories by default, there a few things to adjust if we want to use rpm repositories instead.

**Comment by gbraad** [comment]
the latter refers to the stable repositories you mean?

**Comment by dmsimard** [comment]
Hi, yes. Currently, weirdo repository setup expects two .repo files.
We will need to test the stable release RPM once it is out.
Now that I think about it, though, I'm tempted to leave this part upstream.

The different projects integration tests already set up repositories (trunk or stable rpm) but I've made sure that each project had a toggle or parameters to set differents repos. If I don't use this toggle, the project tests will set up the stable rpm release themselves for their stable branches.

Either way, need a small patch to either use (or not) the toggle or set up the rpm repo within weirdo.

**Comment by gbraad** [comment]
It would also really depend on how your builds are organized;

When set of sources is build, they together from an intermediate build. Based on this whole set of sources and the outcome of the build, this _set_ can be _promoted_ to become a potential release as stable.

However, it feels like currently a _small subset_ of packages are _promoted_ to become 'stable' and therefore the whole set of stable packages have never been tested as a whole, correct?

**Comment by dmsimard** [comment]
I'm not sure I understand the question, tested repositories contain the entire set of packages meant for promotion. Perhaps this documentation can help clear some confusion: http://dlrn.readthedocs.org/en/latest/repositories.html

We test and promote the "delorean" repository regularly. The delorean-deps is fairly static and contains dependencies that are not built automatically by delorean for the most part (i.e, "python-requests").

The thing I can see being a problem is that some packages might not have been properly tested and are promoted because they are part of a set of other packages that have been tested.
For example, we have nothing in our test pipeline that installs and tests magnum. RDO provides a magnum set of packages and these can end up in stable repositories without extensive testing.
Fixing this issue is not part of WeIRDO's scope, though.

**Comment by dmsimard** [comment]
I decided to keep this out of WeIRDO for simplicity's sake. It's sort of out of scope for WeIRDO to explicitely test stable releases.

Either:
WeIRDO manages the repositories itself by setting up trunk repositories and disabling repository management from the upstream job
- or -
  WeIRDO doesn't manage the repositories itself and uses whatever repository the upstream job sets up. In the case of stable branches, this might mean using the stable repositories if that's the the upstream job sets up.

However, I plan on making WeIRDO a bit more generic in terms of repository setup in the future.
