### ISSUE TITLE
Provide support for deploying elsewhere than ci.centos.org

### ISSUE THREAD

**Issue by dmsimard** [rdo-infra/weirdo#5]
Right now weirdo jobs are wired to use the ci.centos node provisioner by default.
We need to have a toggle to either turn off the provisioner entirely (i.e, provision on localhost) or use an arbitrary one.

I had originally designed weirdo with deployment on both ci.centos and openstack clouds in mind so things are already fairly decoupled -- though I slashed the openstack support to keep the scope as narrow and simple as possible.

**Comment by gbraad** [comment]
current provisioning depends on the ci-centos writing an ansible inventory to be able to target `[openstack_nodes]`. just like the `delorean_url`, it would be possible to specify the target as an extra variable such as `--extra-vars target_nodes=142.62.93.17` (for commandline usage). Or what would be the preferred approach? It would be ideal if a different provisioning role could be selected.

**Comment by dmsimard** [comment]
I still need to think about it but basically the ci-centos role will be optional in the playbooks and you would invoke ansible-playbook with an inventory file with localhost inside the openstack_nodes group.

**Comment by gbraad** [comment]
After commenting out the centos-ci provisioning tasks, and providing a basic inventory file, it is possible to run:

`tox -e ansible-playbook -- -i ~/workspace/target -vv playbooks/packstack-scenario001.yml`

where `workspace/target` refers to a basic Ansible inventory file, specifying _localhost_

```
localhost ansible_connection=local

[openstack_nodes]
localhost
```

Correction to earlier: I have tried a remote target, but this failed. Unsure about the reason and had no time to investigate further at this time.

I have only tested PackStack installs using weirdo. However, target
which runs weirdo need to be provisioned with a certain set of tools:

I have only tested PackStack installs using weirdo. However, target
which runs weirdo need to be provisioned with a certain set of tools:

```
$ yum install -y epel-release
$ yum install -y python-pip
$ yum groupinstall -y "Development tools" [--skip-broken]  # issues
with systemtap-devel
$ yum install -y python-devel
$ pip install tox
$ tox [on checkout/workdir]
```

**Comment by dmsimard** [comment]
With the commits that went in today, I decided to give this a try. (fyi: @TristanCacqueray)

I was able to successfully run a full WeIRDO playbook from scratch on a fresh CentOS machine with the following (simple) script: https://gist.github.com/dmsimard/1e1b6fb7123c5c50519c065299f2e47c

There are some little tweaks to do (i.e, the log_destination being a bit weird, still works -- just weird, so I set it manually in the host vars) but it works.
